apiVersion: v1
kind: Service
metadata:
  name: kub-4-svc
  namespace: kub-4
spec:
  selector:
    app: dep
  ports:
    - protocol: TCP
      name: nginx
      port: 9001
      targetPort: 80
    - protocol: TCP
      name: multitool
      port: 9002
      targetPort: 8080